// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJTbDLvtOGuvqbL91HYgOVoU73YE_pKw',
    appId: '1:804268410341:web:1010e34c41675b995e5b0c',
    messagingSenderId: '804268410341',
    projectId: 'jokesapp-9990a',
    authDomain: 'jokesapp-9990a.firebaseapp.com',
    storageBucket: 'jokesapp-9990a.firebasestorage.app',
    measurementId: 'G-SD0JC28198',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkLiESfbehW38XPHc40HXjesKFegUZrio',
    appId: '1:804268410341:android:59f2691751db62df5e5b0c',
    messagingSenderId: '804268410341',
    projectId: 'jokesapp-9990a',
    storageBucket: 'jokesapp-9990a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4fa1hoQH1sFgu6ymuyzFRVCjjekD8z0',
    appId: '1:804268410341:ios:25c6d3add096f77d5e5b0c',
    messagingSenderId: '804268410341',
    projectId: 'jokesapp-9990a',
    storageBucket: 'jokesapp-9990a.firebasestorage.app',
    iosBundleId: 'com.example.mislab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4fa1hoQH1sFgu6ymuyzFRVCjjekD8z0',
    appId: '1:804268410341:ios:25c6d3add096f77d5e5b0c',
    messagingSenderId: '804268410341',
    projectId: 'jokesapp-9990a',
    storageBucket: 'jokesapp-9990a.firebasestorage.app',
    iosBundleId: 'com.example.mislab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNJTbDLvtOGuvqbL91HYgOVoU73YE_pKw',
    appId: '1:804268410341:web:cb0e76921b9f57fe5e5b0c',
    messagingSenderId: '804268410341',
    projectId: 'jokesapp-9990a',
    authDomain: 'jokesapp-9990a.firebaseapp.com',
    storageBucket: 'jokesapp-9990a.firebasestorage.app',
    measurementId: 'G-33CXBE9Q89',
  );
}
